### ISSUE TITLE
Replicate ratings for wptheme content type (Ratings v2.0)

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#16]
http://www.connect2sa.co.za/rigel/wptheme/avada/: I have just edit a review, and it is displayed.
Can you at the top of the page display a 5 star rating and a number of reviews as well?

**Comment by heinvv** [comment]
I fear that I have found some real issues here. 
Sorry for the confusion about this. 

I hope that with my most recent comments, things have been cleared up. 

Please charge the extra hours that you have to make because of this confusion to us. This is not your fault. 

Please find clarification in document attached. 
[rating updates.docx](https://github.com/Forket/connect2sa.co.za_01/files/50793/rating.updates.docx)

**Comment by Forket** [comment]
I'd like to add one aspect:
We'd like to show an average of rating per aspect as well.
Please see REVIEW section on
http://www.connect2sa.co.za/rigel/test/profile/theme_profile.php
http://www.connect2sa.co.za/rigel/test/profile/pro_page.php.

**Comment by heinvv** [comment]
These are the design examples for WP Theme and Member/Developer page. We
forward you more information about it later today.

**Comment by heinvv** [comment]
What is the status of the review + rating sections?
On listing page?
On developer page?
on wp theme page?
on seller page?
on theme developer page?

**Comment by heinvv** [comment]
What is the status of this issue? How far are you?

**Comment by Forket** [comment]
I's almost ready. Because this issue depends on 2 other issues (1 of them done). I plan to release this issue today/tomorrow max

**Comment by heinvv** [comment]
Great!

**Comment by heinvv** [comment]
Perfect

-----Original Message-----

**Comment by Forket** [comment]
>User rating

Done

**Comment by Forket** [comment]
>Rating on top of page

Done

**Comment by Forket** [comment]
>Subrelated issues

Done

**Comment by Forket** [comment]
Please check and confirm.
Here is WPTheme for testing.
http://www.connect2sa.co.za/rigel/wptheme/avada/
Now rating is based on reviews rating.

**Comment by heinvv** [comment]
I just tested the rating system on the Avada page.
Something went wrong.

I reviewed one aspect only. Design. I gave it full score.
But it saved it as 4/5. Can you please check that?

**Comment by heinvv** [comment]
I think your script works fine on wptheme!

There is only another problem from previous developer.
[image: Inline images 1]

When you have a look at vv, you see 3/5 star rating.
The star rating in bottom section is static. It should be dynamic. All of
them of 3/5.

**Comment by heinvv** [comment]
This is on http://www.connect2sa.co.za/rigel/wptheme/avada/

**Comment by heinvv** [comment]
I don't think user rating is working.

I submitted one website review.
I gave 5/5 for design.

Designer is vv60.

Then I went to http://www.connect2sa.co.za/rigel/members/vv60/.

I says 1 review.
But rating isn't active.

While it should say 5/5.

**Comment by Forket** [comment]
>I just tested the rating system on the Avada page.
Something went wrong.
I reviewed one aspect only. Design. I gave it full score.
But it saved it as 4/5. Can you please check that?

it because not correct of DISPLAYING information in reviews list (it's developed by previous developer as I understand). Because if U will take a look at backend than you will see that MY  solution calculated rating correctly.
![snapshot n001_2015-12-21_20-01-10](https://cloud.githubusercontent.com/assets/6735288/11938807/b9025ab0-a81d-11e5-86ab-5ac676752bc4.png)

(1+5+3) / 3 = 3

So AVG rating for theme is 3. And it shows in theme rating
![snapshot n001_2015-12-21_20-03-26](https://cloud.githubusercontent.com/assets/6735288/11938834/ed41763a-a81d-11e5-90b0-bef7744146e9.png)

So, question. Should I under this issue fix displaying of reviews in reviews list?

**Comment by heinvv** [comment]
Yes, can you please fix it first?

-----Original Message-----

**Comment by Forket** [comment]
for clarification: if for example I put just DESIGN = 0 rating in review (other rating like SEO etc  are not applicable) in this case in review rating I should show 5?

**Comment by heinvv** [comment]
I am not sure what you mean.

For wptheme rating: 
Let's we rate one aspect only.
We give that 5. E.g. Design
Then rating of that theme is 5.

For website rating
Exactly the same

For user rating
A user receives the rating of the aspect that he is responsible for
E.g. You are developer of website A
Someone give a 5 for the development of that website
Then you receive rating 5 for that website
Even if the person says design is 2.


-----Original Message-----

**Comment by heinvv** [comment]
Hi Alex,

Sorry wrong topic. I am testing from my phone.

When a new user registers for the website and goes to add website, it doesn't display the API key. It only does it when user logs in for 2nd time.

Can we fix this?



-----Original Message-----

**Comment by heinvv** [comment]
Sorry, wrong issue again

I just created user test10
I added website g

Without webmaster verification etc

And the website was added?

Previously the script checked if webmaster verification API key was present first?

How does it work now?

Does it not check anymore?

Or only later?

And, I haven't checked yet, does it still check for theme moderation?

Originally the idea was
- indicate what theme you use while adding website
- if website moderation script finds wp-content/themes/theme_name in html, then add automatically
- if line isn't found, add to the list of to be moderated

Can you work with that?

About webmaster verification:
I am thinking, when someone adds a page, but webmaster verification API key is absent,
Then
- we could add it to the system already (as long as it gets moderated, see above)
- "owner" is admin
- the link "add developer" to project appears
- none of the developers should be invited nor added to project yet, because there is no verification that these people are webmasters of this project
- the person who added this project, should receive an email, that this website wasn't added, because no webmaster verification

This is important to us. Can you please give us feedback?

-----Original Message-----

**Comment by heinvv** [comment]
I found another issue

I added website g
As user test10

I added myself as a developer

But I received a message to approve myself being added

This shouldn't be this way

When you add yourself, you should be added automatically, without invitation to approve.


-----Original Message-----
From: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>
Sent: ‎2015-‎12-‎22 05:08 PM
To: "Forket/connect2sa.co.za_01" <reply@reply.github.com>; "Forket/connect2sa.co.za_01" <connect2sa.co.za_01@noreply.github.com>
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wptheme contenttype(Ratings v2.0) (#16)

Sorry, wrong issue again

I just created user test10
I added website g

Without webmaster verification etc

And the website was added?

Previously the script checked if webmaster verification API key was present first?

How does it work now?

Does it not check anymore?

Or only later?

And, I haven't checked yet, does it still check for theme moderation?

Originally the idea was
- indicate what theme you use while adding website
- if website moderation script finds wp-content/themes/theme_name in html, then add automatically
- if line isn't found, add to the list of to be moderated

Can you work with that?

About webmaster verification:
I am thinking, when someone adds a page, but webmaster verification API key is absent,
Then
- we could add it to the system already (as long as it gets moderated, see above)
- "owner" is admin
- the link "add developer" to project appears
- none of the developers should be invited nor added to project yet, because there is no verification that these people are webmasters of this project
- the person who added this project, should receive an email, that this website wasn't added, because no webmaster verification

This is important to us. Can you please give us feedback?

**Comment by heinvv** [comment]
Right now the email only asks for approval.

I thought that I last week had given instructions to change the wording and content of that email.


The email should refer to the website that has been added and to the role that the person invited has (e.g. developer).

Can you please check for my messages about that?


-----Original Message-----
From: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>
Sent: ‎2015-‎12-‎22 05:14 PM
To: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>; "Forket/connect2sa.co.za_01" <reply@reply.github.com>; "Forket/connect2sa.co.za_01" <connect2sa.co.za_01@noreply.github.com>
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wpthemecontenttype(Ratings v2.0) (#16)

I found another issue

I added website g
As user test10

I added myself as a developer

But I received a message to approve myself being added

This shouldn't be this way

When you add yourself, you should be added automatically, without invitation to approve.



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:08 PM
To: Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wptheme contenttype(Ratings v2.0) (#16)


Sorry, wrong issue again

I just created user test10
I added website g

Without webmaster verification etc

And the website was added?

Previously the script checked if webmaster verification API key was present first?

How does it work now?

Does it not check anymore?

Or only later?

And, I haven't checked yet, does it still check for theme moderation?

Originally the idea was
- indicate what theme you use while adding website
- if website moderation script finds wp-content/themes/theme_name in html, then add automatically
- if line isn't found, add to the list of to be moderated

Can you work with that?

About webmaster verification:
I am thinking, when someone adds a page, but webmaster verification API key is absent,
Then
- we could add it to the system already (as long as it gets moderated, see above)
- "owner" is admin
- the link "add developer" to project appears
- none of the developers should be invited nor added to project yet, because there is no verification that these people are webmasters of this project
- the person who added this project, should receive an email, that this website wasn't added, because no webmaster verification

This is important to us. Can you please give us feedback?

**Comment by heinvv** [comment]
When I click on approve, nothing happens

I go the webpage of listing g, but the system doesn't add me.

And test10 isn't mentioned as a developer.

-----Original Message-----
From: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>
Sent: ‎2015-‎12-‎22 05:14 PM
To: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>; "Forket/connect2sa.co.za_01" <reply@reply.github.com>; "Forket/connect2sa.co.za_01" <connect2sa.co.za_01@noreply.github.com>
Subject: RE: [connect2sa.co.za_01] Replicate ratings forwpthemecontenttype(Ratings v2.0) (#16)

Right now the email only asks for approval.

I thought that I last week had given instructions to change the wording and content of that email.


The email should refer to the website that has been added and to the role that the person invited has (e.g. developer).

Can you please check for my messages about that?



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:14 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wpthemecontenttype(Ratings v2.0) (#16)


I found another issue

I added website g
As user test10

I added myself as a developer

But I received a message to approve myself being added

This shouldn't be this way

When you add yourself, you should be added automatically, without invitation to approve.



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:08 PM
To: Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wptheme contenttype(Ratings v2.0) (#16)


Sorry, wrong issue again

I just created user test10
I added website g

Without webmaster verification etc

And the website was added?

Previously the script checked if webmaster verification API key was present first?

How does it work now?

Does it not check anymore?

Or only later?

And, I haven't checked yet, does it still check for theme moderation?

Originally the idea was
- indicate what theme you use while adding website
- if website moderation script finds wp-content/themes/theme_name in html, then add automatically
- if line isn't found, add to the list of to be moderated

Can you work with that?

About webmaster verification:
I am thinking, when someone adds a page, but webmaster verification API key is absent,
Then
- we could add it to the system already (as long as it gets moderated, see above)
- "owner" is admin
- the link "add developer" to project appears
- none of the developers should be invited nor added to project yet, because there is no verification that these people are webmasters of this project
- the person who added this project, should receive an email, that this website wasn't added, because no webmaster verification

This is important to us. Can you please give us feedback?

**Comment by heinvv** [comment]
http://www.connect2sa.co.za/rigel/listing/screenshot1/

This page has been added by admin
A developer has been added to the system already

But is still displays the button "delete this website". 
It only should display this button when there are no developers added

-----Original Message-----
From: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>
Sent: ‎2015-‎12-‎22 05:19 PM
To: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>; "Forket/connect2sa.co.za_01" <reply@reply.github.com>; "Forket/connect2sa.co.za_01" <connect2sa.co.za_01@noreply.github.com>
Subject: RE: [connect2sa.co.za_01] Replicate ratingsforwpthemecontenttype(Ratings v2.0) (#16)

When I click on approve, nothing happens

I go the webpage of listing g, but the system doesn't add me.

And test10 isn't mentioned as a developer.


From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:14 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings forwpthemecontenttype(Ratings v2.0) (#16)


Right now the email only asks for approval.

I thought that I last week had given instructions to change the wording and content of that email.


The email should refer to the website that has been added and to the role that the person invited has (e.g. developer).

Can you please check for my messages about that?



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:14 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wpthemecontenttype(Ratings v2.0) (#16)


I found another issue

I added website g
As user test10

I added myself as a developer

But I received a message to approve myself being added

This shouldn't be this way

When you add yourself, you should be added automatically, without invitation to approve.



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:08 PM
To: Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wptheme contenttype(Ratings v2.0) (#16)


Sorry, wrong issue again

I just created user test10
I added website g

Without webmaster verification etc

And the website was added?

Previously the script checked if webmaster verification API key was present first?

How does it work now?

Does it not check anymore?

Or only later?

And, I haven't checked yet, does it still check for theme moderation?

Originally the idea was
- indicate what theme you use while adding website
- if website moderation script finds wp-content/themes/theme_name in html, then add automatically
- if line isn't found, add to the list of to be moderated

Can you work with that?

About webmaster verification:
I am thinking, when someone adds a page, but webmaster verification API key is absent,
Then
- we could add it to the system already (as long as it gets moderated, see above)
- "owner" is admin
- the link "add developer" to project appears
- none of the developers should be invited nor added to project yet, because there is no verification that these people are webmasters of this project
- the person who added this project, should receive an email, that this website wasn't added, because no webmaster verification

This is important to us. Can you please give us feedback?

**Comment by heinvv** [comment]
I tried to send a "delete website" message, and I filled in all fields, except of  phone number, and it said failed, because I hadn't filled in all fields.

Can you please check that?

Can you please change it to check fields before form has been sent?



-----Original Message-----
From: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>
Sent: ‎2015-‎12-‎22 05:24 PM
To: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>; "Forket/connect2sa.co.za_01" <reply@reply.github.com>; "Forket/connect2sa.co.za_01" <connect2sa.co.za_01@noreply.github.com>
Subject: RE: [connect2sa.co.za_01] Replicateratingsforwpthemecontenttype(Ratings v2.0) (#16)

http://www.connect2sa.co.za/rigel/listing/screenshot1/

This page has been added by admin
A developer has been added to the system already

But is still displays the button "delete this website". 
It only should display this button when there are no developers added


From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:19 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratingsforwpthemecontenttype(Ratings v2.0) (#16)


When I click on approve, nothing happens

I go the webpage of listing g, but the system doesn't add me.

And test10 isn't mentioned as a developer.


From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:14 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings forwpthemecontenttype(Ratings v2.0) (#16)


Right now the email only asks for approval.

I thought that I last week had given instructions to change the wording and content of that email.


The email should refer to the website that has been added and to the role that the person invited has (e.g. developer).

Can you please check for my messages about that?



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:14 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wpthemecontenttype(Ratings v2.0) (#16)


I found another issue

I added website g
As user test10

I added myself as a developer

But I received a message to approve myself being added

This shouldn't be this way

When you add yourself, you should be added automatically, without invitation to approve.



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:08 PM
To: Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wptheme contenttype(Ratings v2.0) (#16)


Sorry, wrong issue again

I just created user test10
I added website g

Without webmaster verification etc

And the website was added?

Previously the script checked if webmaster verification API key was present first?

How does it work now?

Does it not check anymore?

Or only later?

And, I haven't checked yet, does it still check for theme moderation?

Originally the idea was
- indicate what theme you use while adding website
- if website moderation script finds wp-content/themes/theme_name in html, then add automatically
- if line isn't found, add to the list of to be moderated

Can you work with that?

About webmaster verification:
I am thinking, when someone adds a page, but webmaster verification API key is absent,
Then
- we could add it to the system already (as long as it gets moderated, see above)
- "owner" is admin
- the link "add developer" to project appears
- none of the developers should be invited nor added to project yet, because there is no verification that these people are webmasters of this project
- the person who added this project, should receive an email, that this website wasn't added, because no webmaster verification

This is important to us. Can you please give us feedback?

**Comment by heinvv** [comment]
http://www.connect2sa.co.za/rigel/listing/dsadas/

This page has no developer, but I don't see a button "add developer"

-----Original Message-----
From: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>
Sent: ‎2015-‎12-‎22 05:29 PM
To: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>; "Forket/connect2sa.co.za_01" <reply@reply.github.com>; "Forket/connect2sa.co.za_01" <connect2sa.co.za_01@noreply.github.com>
Subject: RE: [connect2sa.co.za_01]Replicateratingsforwpthemecontenttype(Ratings v2.0) (#16)

I tried to send a "delete website" message, and I filled in all fields, except of  phone number, and it said failed, because I hadn't filled in all fields.

Can you please check that?

Can you please change it to check fields before form has been sent?




From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:24 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicateratingsforwpthemecontenttype(Ratings v2.0) (#16)


http://www.connect2sa.co.za/rigel/listing/screenshot1/

This page has been added by admin
A developer has been added to the system already

But is still displays the button "delete this website". 
It only should display this button when there are no developers added


From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:19 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratingsforwpthemecontenttype(Ratings v2.0) (#16)


When I click on approve, nothing happens

I go the webpage of listing g, but the system doesn't add me.

And test10 isn't mentioned as a developer.


From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:14 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings forwpthemecontenttype(Ratings v2.0) (#16)


Right now the email only asks for approval.

I thought that I last week had given instructions to change the wording and content of that email.


The email should refer to the website that has been added and to the role that the person invited has (e.g. developer).

Can you please check for my messages about that?



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:14 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wpthemecontenttype(Ratings v2.0) (#16)


I found another issue

I added website g
As user test10

I added myself as a developer

But I received a message to approve myself being added

This shouldn't be this way

When you add yourself, you should be added automatically, without invitation to approve.



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:08 PM
To: Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wptheme contenttype(Ratings v2.0) (#16)


Sorry, wrong issue again

I just created user test10
I added website g

Without webmaster verification etc

And the website was added?

Previously the script checked if webmaster verification API key was present first?

How does it work now?

Does it not check anymore?

Or only later?

And, I haven't checked yet, does it still check for theme moderation?

Originally the idea was
- indicate what theme you use while adding website
- if website moderation script finds wp-content/themes/theme_name in html, then add automatically
- if line isn't found, add to the list of to be moderated

Can you work with that?

About webmaster verification:
I am thinking, when someone adds a page, but webmaster verification API key is absent,
Then
- we could add it to the system already (as long as it gets moderated, see above)
- "owner" is admin
- the link "add developer" to project appears
- none of the developers should be invited nor added to project yet, because there is no verification that these people are webmasters of this project
- the person who added this project, should receive an email, that this website wasn't added, because no webmaster verification

This is important to us. Can you please give us feedback?


From: Aleksandr
Sent: �=8

[The entire original message is not included.]

**Comment by heinvv** [comment]
I am not sure what is the difference between http://www.connect2sa.co.za/rigel/listing/backform/ and http://www.connect2sa.co.za/rigel/listing/dsadas/

None of them seems to have any developers info, but the buttons are different.

Or is this because developers have been invited for the 2nd project already?

-----Original Message-----
From: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>
Sent: ‎2015-‎12-‎22 05:36 PM
To: "Hein van Vlastuin" <heinvanvlastuin@gmail.com>; "Forket/connect2sa.co.za_01" <reply@reply.github.com>; "Forket/connect2sa.co.za_01" <connect2sa.co.za_01@noreply.github.com>
Subject: RE:[connect2sa.co.za_01]Replicateratingsforwpthemecontenttype(Ratings v2.0)(#16)

http://www.connect2sa.co.za/rigel/listing/dsadas/

This page has no developer, but I don't see a button "add developer"


From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:29 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01]Replicateratingsforwpthemecontenttype(Ratings v2.0) (#16)


I tried to send a "delete website" message, and I filled in all fields, except of  phone number, and it said failed, because I hadn't filled in all fields.

Can you please check that?

Can you please change it to check fields before form has been sent?




From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:24 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicateratingsforwpthemecontenttype(Ratings v2.0) (#16)


http://www.connect2sa.co.za/rigel/listing/screenshot1/

This page has been added by admin
A developer has been added to the system already

But is still displays the button "delete this website". 
It only should display this button when there are no developers added


From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:19 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratingsforwpthemecontenttype(Ratings v2.0) (#16)


When I click on approve, nothing happens

I go the webpage of listing g, but the system doesn't add me.

And test10 isn't mentioned as a developer.


From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:14 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings forwpthemecontenttype(Ratings v2.0) (#16)


Right now the email only asks for approval.

I thought that I last week had given instructions to change the wording and content of that email.


The email should refer to the website that has been added and to the role that the person invited has (e.g. developer).

Can you please check for my messages about that?



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:14 PM
To: Hein van Vlastuin; Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wpthemecontenttype(Ratings v2.0) (#16)


I found another issue

I added website g
As user test10

I added myself as a developer

But I received a message to approve myself being added

This shouldn't be this way

When you add yourself, you should be added automatically, without invitation to approve.



From: Hein van Vlastuin
Sent: ‎2015-‎12-‎22 05:08 PM
To: Forket/connect2sa.co.za_01; Forket/connect2sa.co.za_01
Subject: RE: [connect2sa.co.za_01] Replicate ratings for wptheme contenttype(Ratings v2.0) (#16)


Sorry, wrong issue again

I just created user test10
I added website g

Without webmaster verification etc

And the website was added?

Previously the script checked if webmaster verification API key was present first?

How does it work now?

Does it not check anymore?

[The entire original message is not included.]

**Comment by Forket** [comment]
>When a new user registers for the website and goes to add website, it doesn't display the API key. It only does it when user logs in for 2nd time.

I temporary disables this in order to develop and test. Because for example when I put google.com.ua - it asks me for KEY :) and I'm not google owner :)

**Comment by heinvv** [comment]
Okay, cool.

I understand.

I assume that my other comments and questions are clear?

**Comment by Forket** [comment]
>I found another issue
I added website g
As user test10
I added myself as a developer
But I received a message to approve myself being added
This shouldn't be this way
When you add yourself, you should be added automatically, without invitation to approve.

Fixed

**Comment by Forket** [comment]
>The email should refer to the website that has been added and to the role that the person invited has (e.g. developer).

I can't find it :( maybe lost in comments. could you please send it again? Thanks

**Comment by heinvv** [comment]
Great

-----Original Message-----

**Comment by Forket** [comment]
>When I click on approve, nothing happens
I go the webpage of listing g, but the system doesn't add me.
And test10 isn't mentioned as a developer.

Could you check this again, because I've checked twice - it works.

**Comment by Forket** [comment]
>http://www.connect2sa.co.za/rigel/listing/screenshot1/
This page has been added by admin
A developer has been added to the system already
But is still displays the button "delete this website".
It only should display this button when there are no developers added

You asked to show it only when added by admin. Please refer issue #13. But it's easy to extend, so don't worry. I've done it. You can check.

**Comment by heinvv** [comment]
I have created a new issue about this. 
About adding developers
There is the email template


-----Original Message-----

**Comment by Forket** [comment]
>I tried to send a "delete website" message, and I filled in all fields, except of  phone number, and it said failed, because I hadn't filled in all fields.
Can you please check that?
Can you please change it to check fields before form has been sent?

I'll add this as separate issue. It need client side validation (javascript/jquery). Issue #34

**Comment by heinvv** [comment]
This is not about verification
When a new user registers and goes to add listing page, it should display API key.
But it only shows it when you load the form for the second time

-----Original Message-----

**Comment by Forket** [comment]
>This is not about verification
When a new user registers and goes to add listing page, it should display API key.
But it only shows it when you load the form for the second time

I don't know about logic. Have to debug. It came from previous developer. Will fix it.

**Comment by Forket** [comment]
>http://www.connect2sa.co.za/rigel/listing/dsadas/
This page has no developer, but I don't see a button "add developer"

This is old listing (created about 2 months ago). Please don't use old listing for testing because they are not correct. As I wrote before: ratings system changed and changed the way (in code) of adding developers. It means that all old listings are not actual.

**Comment by Forket** [comment]
>I am not sure what is the difference between http://www.connect2sa.co.za/rigel/listing/backform/ and http://www.connect2sa.co.za/rigel/listing/dsadas/
None of them seems to have any developers info, but the buttons are different.
Or is this because developers have been invited for the 2nd project already?

Same comment as previous.
http://www.connect2sa.co.za/rigel/listing/backform/  - it's NEW listing
http://www.connect2sa.co.za/rigel/listing/dsadas/ - OLD listing

Maybe in order not to make a mess - delete all old listings?

**Comment by heinvv** [comment]
Yes, can please delete old listings?

How far are you with development of rating and review process?

-----Original Message-----

**Comment by Forket** [comment]
In admin side you have separating rating for LISTING and for THEMES.
What is purpose of this? Can I store ratings for LISTINGs and THEMEs in one section?
![snapshot n001_2015-12-28_10-33-46](https://cloud.githubusercontent.com/assets/6735288/12016708/874b6ada-ad4e-11e5-84e8-5ad6f57325c2.png)

**Comment by heinvv** [comment]
I am not sure

Ratings of website listings are used for website listings itself and for ratings of website developers.

Ratings of themes are used to rare themes, theme
sellers and theme developers.

Process is similar, but content is different.

The aspects that we rare of website listings are different from themes as well.

As long as all these aspects and the content is dealt with separately, then it is fine.

I think it makes sense to save data separately.

What do you think?
Is this clear?

-----Original Message-----

**Comment by Forket** [comment]
I'd make it in ONE section and just also put type of review.
So you will have list of all reviews and there would be information about to which object this review belongs (to listing, to theme or anything else)

**Comment by Forket** [comment]
Question about calculating AVG rating.
Take a look at screenshot. If I rated just 2 aspects, AVG rating should be
* (5+5)/2 = 5
OR
* (5+5+0+0+0+0+0+0)/8 = 1.2

![snapshot n001_2015-12-28_12-13-19](https://cloud.githubusercontent.com/assets/6735288/12017893/93a62f8c-ad5c-11e5-9077-cbaf771dc91f.png)
)

**Comment by Forket** [comment]
Questions about user profile and reviews label.
This should show number of reviews which user WROTE (user as author of review)
OR
number of reviews WHERE USER MENTIONED (as designer, developer etc)
![snapshot n001_2015-12-28_18-45-19](https://cloud.githubusercontent.com/assets/6735288/12022757/2f3899f4-ad93-11e5-86b2-8dc512b41963.png)

**Comment by heinvv** [comment]
Answer: This should show number of reviews which user WROTE (user as author
of review)

E.g.
website listing a

reviews by
1. user a
2. user b
3. user c
4. user d
5. user e
6. user f
7. user g

In this case : 7 reviews.

**Comment by Forket** [comment]
OK.
I should tell that reviews and rating system finally ready. Need you to test it and provide feedback.

**Comment by heinvv** [comment]
In this case: Average is 5

-----Original Message-----

**Comment by heinvv** [comment]
Great!

I am holiday, but I'll try to make some time for testing tomorrow or day after tomorrow 



-----Original Message-----

**Comment by Forket** [comment]
As for testing. 
Please create new object for tests. 
Now I will delete all reviews/listings/themes/users
