### ISSUE TITLE
Speed of submitting a listing

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#21]
Please see info in word document
[20151207 speed of submitting a listing.docx](https://github.com/Forket/connect2sa.co.za_01/files/53934/20151207.speed.of.submitting.a.listing.docx)

**Comment by Forket** [comment]
cron-job is the best solution in this case. Agree to use this option?

**Comment by heinvv** [comment]
Perfect

-----Original Message-----

**Comment by Forket** [comment]
So. I finally recoded solution to take screenshot using cron job.
Job starts wight after submitting and don't impact on performance.

**Comment by heinvv** [comment]
Thank you so much for your updates.
I'll get back to you on Monday

What other updates do you planned first now?


-----Original Message-----

**Comment by heinvv** [comment]
Great!

Let me test it, and than afterwards I can stop other service?


-----Original Message-----

**Comment by Forket** [comment]
No. 
I still use this service.
In this issue i've changed screenshot solution to work as cron job (i had to rewrite it). 
In order to develop custom solution for TAKING site screenshots I wait for your decision about hosting.
And when you will decide - i'll develop custom solution which will also use this approach (working as cron job).
cron job is used just in order to not to make user wait while taking screenshot. (in cron job it's taking as background)

**Comment by heinvv** [comment]
Thanks for the update 

-----Original Message-----
